# Generated by Django 2.2.7 on 2019-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Food and Beverages'), (2, 'Beauty shops'), (3, 'Social Amentity'), (4, 'Entertainment'), (5, 'Housing')])),
            ],
        ),
    ]
