# Generated by Django 2.2.7 on 2019-11-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.Neighbourhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
