# Generated by Django 2.2.7 on 2019-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0004_auto_20191128_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(default='dummy_neighbourhood.jpg', upload_to='neighbourhood_avatars'),
        ),
    ]
