# Generated by Django 2.2.7 on 2019-11-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_neighbourhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='business.jpg', upload_to='business_avatars'),
        ),
    ]
